import = [
  "/usr/lib/node_modules/alacritty-themes/themes/One-Dark.toml"
]

[window]
startup_mode = "Windowed"
dynamic_title = true
opacity = 0.1


[shell]
program = "/usr/bin/fish"
args = ["--login"]

[cursor]
style = { shape = "Underline", blinking = "Always" }

[font]
normal.family = "PixelCode"
normal.style = "Regular"

bold.family = "PixelCode"
bold.style = "Bold"

size = 12.0

offset.x = 0
offset.y = 0


# [env]
# ZDOTDIR = "/home/arx/.config/zsh"
